window.GAME_GALLERY_DATA = [
  { title: "Anomaly Project", rating: 3, comment: "Just find anomaly, very boring.", images: ["Anomalyproject.png"] },
  { title: "Astroneer", rating: 4, comment: "Very special survival game.", images: ["Astroneer.png"] },
  { title: "Backroom", rating: 5, comment: "Perfect game to play with friends.", images: ["Backroom.png"] },
  { title: "Backroom 2", rating: 1, comment: "Boring game, just good graphics.", images: ["Backroom2.png"] },
  { title: "Backrooms Lost Runners", rating: 4, comment: "Not bad, very cool idea.", images: ["Backrooms Lost Runners.png"] },
  { title: "Backseat Drivers", rating: 2, comment: "Boring game, only 1 driver and 3 others will be the guide.", images: ["Backseat Drivers.png"] },
  { title: "BET", rating: 5, comment: "Very fun and interesting game, recommended.", images: ["BET.png"] },
  { title: "Big Walk", images: ["Big Walk 1.png", "Big Walk 2.png"] },
  { title: "Biped 2", rating: 3, comment: "Not bad, but full of bugs.", images: ["Biped 2.png"] },
  { title: "Boo Men", rating: 2, comment: "Very boring game, just keep chasing your friends.", images: ["Boo Men.png"] },
  { title: "Burgling Gnomes", rating: 2, comment: "Boring game, too overrated.", images: ["Burgling Gnomes.png"] },
  { title: "Car Service Together", rating: 3, comment: "Not bad actually, can customize different car haha.", images: ["Car Service Together.png"] },
  { title: "Civilization VI", rating: 5, comment: "Good game but very time consuming.", images: ["Civilization VI.png"] },
  { title: "Cloudheim", rating: 3, comment: "Just like genshin but just with own base.", images: ["Cloudheim.png"] },
  { title: "Core Keeper", rating: 4, comment: "Not bad, many thing to do and build.", images: ["CoreKeeper.png"] },
  { title: "Deep Rock Galactic", rating: 1, comment: "Boring game.", images: ["Deep Rock Galatic.png"] },
  { title: "Double Dealer", rating: 3, comment: "Decent game, interesting at first and get bored very quickly.", images: ["Double Dealer.png"] },
  {
    title: "Dragonwilds",
    rating: 4,
    comment: "Not bad, but just too grindy.",
    images: [
      "Dragonwilds 1.png",
      "Dragonwilds 2.png",
      "Dragonwilds 3.png",
      "Dragonwilds 4.png",
      "Dragonwilds 5.png",
      "Dragonwilds 6.png",
      "Dragonwilds 7.png"
    ]
  },
  { title: "Drive Beyond", rating: 3, comment: "Very new game idea, but it is incompleted game.", images: ["Drive Beyond.png"] },
  { title: "Ember Knights", images: ["Ember Knights.png"] },
  { title: "Friendly Steps", rating: 2, comment: "Decent game, require all friends to make 0 mistakes.", images: ["Friendly Steps.png"] },
  { title: "Frog Sqwad", rating: 1, comment: "Boring game, just to find foods.", images: ["Frog Sqwad.png"] },
  { title: "Gamble With Your Friends", rating: 2, comment: "Interesting at first and get bored very quickly.", images: ["Gamble With Your Friends.png"] },
  { title: "Goblin Company", rating: 1, comment: "Bad game.", images: ["Goblin Company.png"] },
  { title: "Grounded", rating: 3, comment: "Not bad.", images: ["Grounded.png", "Grounded.jpg"] },
  { title: "Grounded 2", rating: 3, comment: "Not bad, but just grindy.", images: ["Grounded 2.png"] },
  { title: "Guilty as Sock", rating: 1, comment: "Dont know how to play at all.", images: ["Guiltyassock.png"] },
  { title: "Gunfire Reborn", images: ["Gunfire Reborn 1.png", "Gunfire Reborn 2.png"] },
  { title: "Headliners", rating: 3, comment: "Went to take photos of monster, overall not bad.", images: ["Headliners.jpg"] },
  { title: "How To Fish", images: ["How To Fish.png", "How To Fish 2.png"] },
  { title: "Ivoyker", rating: 3, comment: "Cool idea just like Jumanji.", images: ["Ivoyker.png"] },
  { title: "Kebab Chef", rating: 2, comment: "Boring game.", images: ["Kebab Chef.JPG"] },
  { title: "LockDown", rating: 4, comment: "Play with friends is fun.", images: ["LockDown.png"] },
  { title: "Machine Party", images: ["Machine Party 1.png", "Machine Party 2.png"] },
  { title: "Mecha Chameleon", rating: 4, comment: "Not bad, played with few strangers.", images: ["Mecha Chameleon.png"] },
  { title: "Midnight Shifts", images: ["Midnight Shifts 1.png", "Midnight Shifts 2.png"] },
  { title: "Monster Pet Shop", rating: 5, comment: "Fun game actually but the game is incomplete.", images: ["Monster Pet Shop.png"] },
  { title: "Pico", rating: 1, comment: "Fuck this game.", images: ["Pico.jpeg"] },
  { title: "Pummel Party", rating: 4, comment: "Quite fun to play with friends.", images: ["Pummel party.png"] },
  { title: "Raft", rating: 5, comment: "Perfect game.", images: ["Raft.png"] },
  { title: "Raiders of Blackveil", rating: 3, comment: "Decent game.", images: ["Raiders of Blackveil.png"] },
  { title: "Reanimal", rating: 3, comment: "Decent game.", images: ["Reanimal.png"] },
  { title: "Revenge of the Savage Planet", rating: 5, comment: "Perfect game to play with one other friend.", images: ["Revenge of the Savage Planet.png"] },
  { title: "Romestead", rating: 5, comment: "Very cool idea, quite fun.", images: ["Romestead.png"] },
  { title: "RV There Yet", rating: 3, comment: "At first is easy and it is getting harder at the end.", images: ["RV There Yet.png"] },
  { title: "Schedule I", rating: 5, comment: "Not bad, quite fun.", images: ["Schedule  I.png"] },
  { title: "Sephiria", images: ["Sephiria.png"] },
  { title: "Shape of Dream", rating: 5, comment: "Totally recommended, best game played so far.", images: ["Shape of Dream.png"] },
  { title: "Son of the Forest", rating: 3, comment: "Still ok.", images: ["Son of the Forest.png", "Sunoftheforest.png"] },
  { title: "Split Fiction", rating: 5, comment: "Good game to play with friends, good graphics, fun play style.", images: ["Split Fiction.jpeg"] },
  { title: "Starseeker", rating: 1, comment: "Bad compared to first version.", images: ["Starseeker.png"] },
  { title: "Subnautica", rating: 4, comment: "Not bad.", images: ["Subnautica.png"] },
  { title: "It Takes Two", rating: 5, comment: "Definitely recommended.", images: ["Takes Two.png"] },
  { title: "Task Time", rating: 2, comment: "Get bored very fast.", images: ["TaskTime.png"] },
  { title: "Ultimate Chicken Horse", rating: 2, comment: "Get bored very fast.", images: ["Ultimate Chicken Horse.png"] },
  { title: "Wangzhe", rating: 3, comment: "Boring.........", images: ["Wangzhe.jpeg"] },
  { title: "Waterpark Simulator", images: ["Waterpark Simulator.png"] },
  { title: "Zort", rating: 5, comment: "Quite fun to play with friends", images: ["Zort.png"] }
];
